apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::925425186577:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YC3O7L1EIEVV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::925425186577:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-05T11:44:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15717"
  uid: 0ce5901e-9af6-40a6-81f8-ec9b12cf36f4
